# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Pharadas\Documents\repos\Mauve

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Pharadas\Documents\repos\Mauve

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Pharadas\Documents\repos\Mauve\CMakeFiles C:\Users\Pharadas\Documents\repos\Mauve\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Pharadas\Documents\repos\Mauve\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Mauve

# Build rule for target.
Mauve: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Mauve
.PHONY : Mauve

# fast build rule for target.
Mauve/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/build
.PHONY : Mauve/fast

include/engine/buffer_helper.obj: include/engine/buffer_helper.cpp.obj
.PHONY : include/engine/buffer_helper.obj

# target to build an object file
include/engine/buffer_helper.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/buffer_helper.cpp.obj
.PHONY : include/engine/buffer_helper.cpp.obj

include/engine/buffer_helper.i: include/engine/buffer_helper.cpp.i
.PHONY : include/engine/buffer_helper.i

# target to preprocess a source file
include/engine/buffer_helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/buffer_helper.cpp.i
.PHONY : include/engine/buffer_helper.cpp.i

include/engine/buffer_helper.s: include/engine/buffer_helper.cpp.s
.PHONY : include/engine/buffer_helper.s

# target to generate assembly for a file
include/engine/buffer_helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/buffer_helper.cpp.s
.PHONY : include/engine/buffer_helper.cpp.s

include/engine/descriptors/descriptor.obj: include/engine/descriptors/descriptor.cpp.obj
.PHONY : include/engine/descriptors/descriptor.obj

# target to build an object file
include/engine/descriptors/descriptor.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/descriptors/descriptor.cpp.obj
.PHONY : include/engine/descriptors/descriptor.cpp.obj

include/engine/descriptors/descriptor.i: include/engine/descriptors/descriptor.cpp.i
.PHONY : include/engine/descriptors/descriptor.i

# target to preprocess a source file
include/engine/descriptors/descriptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/descriptors/descriptor.cpp.i
.PHONY : include/engine/descriptors/descriptor.cpp.i

include/engine/descriptors/descriptor.s: include/engine/descriptors/descriptor.cpp.s
.PHONY : include/engine/descriptors/descriptor.s

# target to generate assembly for a file
include/engine/descriptors/descriptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/descriptors/descriptor.cpp.s
.PHONY : include/engine/descriptors/descriptor.cpp.s

include/engine/device/device.obj: include/engine/device/device.cpp.obj
.PHONY : include/engine/device/device.obj

# target to build an object file
include/engine/device/device.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/device/device.cpp.obj
.PHONY : include/engine/device/device.cpp.obj

include/engine/device/device.i: include/engine/device/device.cpp.i
.PHONY : include/engine/device/device.i

# target to preprocess a source file
include/engine/device/device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/device/device.cpp.i
.PHONY : include/engine/device/device.cpp.i

include/engine/device/device.s: include/engine/device/device.cpp.s
.PHONY : include/engine/device/device.s

# target to generate assembly for a file
include/engine/device/device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/device/device.cpp.s
.PHONY : include/engine/device/device.cpp.s

include/engine/engine.obj: include/engine/engine.cpp.obj
.PHONY : include/engine/engine.obj

# target to build an object file
include/engine/engine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/engine.cpp.obj
.PHONY : include/engine/engine.cpp.obj

include/engine/engine.i: include/engine/engine.cpp.i
.PHONY : include/engine/engine.i

# target to preprocess a source file
include/engine/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/engine.cpp.i
.PHONY : include/engine/engine.cpp.i

include/engine/engine.s: include/engine/engine.cpp.s
.PHONY : include/engine/engine.s

# target to generate assembly for a file
include/engine/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/engine.cpp.s
.PHONY : include/engine/engine.cpp.s

include/engine/helper_functions.obj: include/engine/helper_functions.cpp.obj
.PHONY : include/engine/helper_functions.obj

# target to build an object file
include/engine/helper_functions.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/helper_functions.cpp.obj
.PHONY : include/engine/helper_functions.cpp.obj

include/engine/helper_functions.i: include/engine/helper_functions.cpp.i
.PHONY : include/engine/helper_functions.i

# target to preprocess a source file
include/engine/helper_functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/helper_functions.cpp.i
.PHONY : include/engine/helper_functions.cpp.i

include/engine/helper_functions.s: include/engine/helper_functions.cpp.s
.PHONY : include/engine/helper_functions.s

# target to generate assembly for a file
include/engine/helper_functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/helper_functions.cpp.s
.PHONY : include/engine/helper_functions.cpp.s

include/engine/material/material.obj: include/engine/material/material.cpp.obj
.PHONY : include/engine/material/material.obj

# target to build an object file
include/engine/material/material.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/material/material.cpp.obj
.PHONY : include/engine/material/material.cpp.obj

include/engine/material/material.i: include/engine/material/material.cpp.i
.PHONY : include/engine/material/material.i

# target to preprocess a source file
include/engine/material/material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/material/material.cpp.i
.PHONY : include/engine/material/material.cpp.i

include/engine/material/material.s: include/engine/material/material.cpp.s
.PHONY : include/engine/material/material.s

# target to generate assembly for a file
include/engine/material/material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/material/material.cpp.s
.PHONY : include/engine/material/material.cpp.s

include/engine/mesh/mesh.obj: include/engine/mesh/mesh.cpp.obj
.PHONY : include/engine/mesh/mesh.obj

# target to build an object file
include/engine/mesh/mesh.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/mesh/mesh.cpp.obj
.PHONY : include/engine/mesh/mesh.cpp.obj

include/engine/mesh/mesh.i: include/engine/mesh/mesh.cpp.i
.PHONY : include/engine/mesh/mesh.i

# target to preprocess a source file
include/engine/mesh/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/mesh/mesh.cpp.i
.PHONY : include/engine/mesh/mesh.cpp.i

include/engine/mesh/mesh.s: include/engine/mesh/mesh.cpp.s
.PHONY : include/engine/mesh/mesh.s

# target to generate assembly for a file
include/engine/mesh/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/mesh/mesh.cpp.s
.PHONY : include/engine/mesh/mesh.cpp.s

include/engine/pipeline/pipeline.obj: include/engine/pipeline/pipeline.cpp.obj
.PHONY : include/engine/pipeline/pipeline.obj

# target to build an object file
include/engine/pipeline/pipeline.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/pipeline/pipeline.cpp.obj
.PHONY : include/engine/pipeline/pipeline.cpp.obj

include/engine/pipeline/pipeline.i: include/engine/pipeline/pipeline.cpp.i
.PHONY : include/engine/pipeline/pipeline.i

# target to preprocess a source file
include/engine/pipeline/pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/pipeline/pipeline.cpp.i
.PHONY : include/engine/pipeline/pipeline.cpp.i

include/engine/pipeline/pipeline.s: include/engine/pipeline/pipeline.cpp.s
.PHONY : include/engine/pipeline/pipeline.s

# target to generate assembly for a file
include/engine/pipeline/pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/pipeline/pipeline.cpp.s
.PHONY : include/engine/pipeline/pipeline.cpp.s

include/engine/texture/texture.obj: include/engine/texture/texture.cpp.obj
.PHONY : include/engine/texture/texture.obj

# target to build an object file
include/engine/texture/texture.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/texture/texture.cpp.obj
.PHONY : include/engine/texture/texture.cpp.obj

include/engine/texture/texture.i: include/engine/texture/texture.cpp.i
.PHONY : include/engine/texture/texture.i

# target to preprocess a source file
include/engine/texture/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/texture/texture.cpp.i
.PHONY : include/engine/texture/texture.cpp.i

include/engine/texture/texture.s: include/engine/texture/texture.cpp.s
.PHONY : include/engine/texture/texture.s

# target to generate assembly for a file
include/engine/texture/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/texture/texture.cpp.s
.PHONY : include/engine/texture/texture.cpp.s

include/engine/window/window.obj: include/engine/window/window.cpp.obj
.PHONY : include/engine/window/window.obj

# target to build an object file
include/engine/window/window.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/window/window.cpp.obj
.PHONY : include/engine/window/window.cpp.obj

include/engine/window/window.i: include/engine/window/window.cpp.i
.PHONY : include/engine/window/window.i

# target to preprocess a source file
include/engine/window/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/window/window.cpp.i
.PHONY : include/engine/window/window.cpp.i

include/engine/window/window.s: include/engine/window/window.cpp.s
.PHONY : include/engine/window/window.s

# target to generate assembly for a file
include/engine/window/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/window/window.cpp.s
.PHONY : include/engine/window/window.cpp.s

include/engine/world_object/world_object.obj: include/engine/world_object/world_object.cpp.obj
.PHONY : include/engine/world_object/world_object.obj

# target to build an object file
include/engine/world_object/world_object.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/world_object/world_object.cpp.obj
.PHONY : include/engine/world_object/world_object.cpp.obj

include/engine/world_object/world_object.i: include/engine/world_object/world_object.cpp.i
.PHONY : include/engine/world_object/world_object.i

# target to preprocess a source file
include/engine/world_object/world_object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/world_object/world_object.cpp.i
.PHONY : include/engine/world_object/world_object.cpp.i

include/engine/world_object/world_object.s: include/engine/world_object/world_object.cpp.s
.PHONY : include/engine/world_object/world_object.s

# target to generate assembly for a file
include/engine/world_object/world_object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/include/engine/world_object/world_object.cpp.s
.PHONY : include/engine/world_object/world_object.cpp.s

source/main.obj: source/main.cpp.obj
.PHONY : source/main.obj

# target to build an object file
source/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/source/main.cpp.obj
.PHONY : source/main.cpp.obj

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Mauve.dir\build.make CMakeFiles/Mauve.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Mauve
	@echo ... include/engine/buffer_helper.obj
	@echo ... include/engine/buffer_helper.i
	@echo ... include/engine/buffer_helper.s
	@echo ... include/engine/descriptors/descriptor.obj
	@echo ... include/engine/descriptors/descriptor.i
	@echo ... include/engine/descriptors/descriptor.s
	@echo ... include/engine/device/device.obj
	@echo ... include/engine/device/device.i
	@echo ... include/engine/device/device.s
	@echo ... include/engine/engine.obj
	@echo ... include/engine/engine.i
	@echo ... include/engine/engine.s
	@echo ... include/engine/helper_functions.obj
	@echo ... include/engine/helper_functions.i
	@echo ... include/engine/helper_functions.s
	@echo ... include/engine/material/material.obj
	@echo ... include/engine/material/material.i
	@echo ... include/engine/material/material.s
	@echo ... include/engine/mesh/mesh.obj
	@echo ... include/engine/mesh/mesh.i
	@echo ... include/engine/mesh/mesh.s
	@echo ... include/engine/pipeline/pipeline.obj
	@echo ... include/engine/pipeline/pipeline.i
	@echo ... include/engine/pipeline/pipeline.s
	@echo ... include/engine/texture/texture.obj
	@echo ... include/engine/texture/texture.i
	@echo ... include/engine/texture/texture.s
	@echo ... include/engine/window/window.obj
	@echo ... include/engine/window/window.i
	@echo ... include/engine/window/window.s
	@echo ... include/engine/world_object/world_object.obj
	@echo ... include/engine/world_object/world_object.i
	@echo ... include/engine/world_object/world_object.s
	@echo ... source/main.obj
	@echo ... source/main.i
	@echo ... source/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

